// <auto-generated />
namespace RepositoryInDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ClientDBv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClientDBv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202305272022453_ClientDB-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
